<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
echo $this->headMeta();
echo $this->headTitle();
echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-3.6.3.min.js') . "\n";
echo $this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.943/build/pdf.min.js') . "\n";
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.css') . "\n";
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');
?>
</head>
<body>
<div id="content">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>